const { config } = global.GoatBot;
const Canvas = require("canvas");
const fs = require("fs-extra");
const path = require("path");
const axios = require("axios");

module.exports = {
  config: {
    name: "balance",
    aliases: ["bal", "money"],
    version: "2.1.0",
    author: "Fixed by siyuu",
    countDown: 1,
    role: 0,
    description: "View balance with Facebook profile picture",
    category: "economy"
  },

  onStart: async function ({ message, usersData, event, args, api }) {
    const senderID = event.senderID;
    const targetUID = event.messageReply ? event.messageReply.senderID : (event.mentions && Object.keys(event.mentions)[0]) || senderID;

    let userData = (await usersData.get(targetUID)) || { money: "0", name: null };
    let displayName = userData.name || "Unknown User";

    try {
      const info = await api.getUserInfo([targetUID]);
      if (info && info[targetUID] && info[targetUID].name) displayName = info[targetUID].name;
    } catch(e){}

    const balanceRaw = Number(userData.money || 0);
    const balancePretty = formatMoney(balanceRaw);

    const waitMsg = await message.reply("⏳ Generating your balance card…");
    setTimeout(() => { try { message.unsend(waitMsg.messageID); } catch(e){} }, 1500);

    let avatarImage = null;
    try {
      const url = `https://graph.facebook.com/${targetUID}/picture?width=512&height=512`;
      const res = await axios.get(url, { responseType: "arraybuffer", timeout: 7000 });
      avatarImage = await Canvas.loadImage(Buffer.from(res.data, "binary"));
    } catch(e){ avatarImage = null; }

    try {
      const imgPath = await generateBalanceCard(targetUID, displayName, balancePretty, avatarImage);
      await message.reply({ body: "", attachment: fs.createReadStream(imgPath) });
      setTimeout(() => fs.unlink(imgPath).catch(() => {}), 7000);
    } catch(e){
      return message.reply(`❌ Failed to generate balance card for ${displayName}.`);
    }

    function formatMoney(num){
      if(num >= 1e12) return (num/1e12).toFixed(2)+"T";
      if(num >= 1e9) return (num/1e9).toFixed(2)+"B";
      if(num >= 1e6) return (num/1e6).toFixed(2)+"M";
      if(num >= 1e3) return (num/1e3).toFixed(2)+"K";
      return num.toString();
    }

    async function generateBalanceCard(uid, name, bal, avatarImg){
      const w = 900, h = 480;
      const canvas = Canvas.createCanvas(w,h);
      const ctx = canvas.getContext("2d");

      const g = ctx.createLinearGradient(0,0,w,h);
      g.addColorStop(0, "#3b1f5a");
      g.addColorStop(1, "#7b3fb6");
      ctx.fillStyle = g;
      ctx.fillRect(0,0,w,h);

      roundRect(ctx, 44,44,w-88,h-88,20,true,false);

      // Avatar
      const avS = 120;
      const avX = 44 + 60, avY = 44 + 70;
      ctx.save();
      ctx.beginPath();
      ctx.arc(avX + avS/2,avY + avS/2,avS/2,0,Math.PI*2);
      ctx.closePath();
      ctx.clip();
      if(avatarImg) ctx.drawImage(avatarImg,avX,avY,avS,avS);
      else{
        ctx.fillStyle = "rgba(255,255,255,0.12)";
        ctx.fillRect(avX,avY,avS,avS);
        ctx.fillStyle = "#fff"; ctx.font = "bold 42px Sans";
        const initials = getInitials(name);
        const m = ctx.measureText(initials);
        ctx.fillText(initials,avX+avS/2 - m.width/2,avY+avS/2 + 15);
      }
      ctx.restore();

      // Name & UID
      ctx.fillStyle = "#fff"; ctx.font = "700 36px Sans";
      ctx.fillText(name, avX + avS + 30, avY + 40);
      ctx.font = "500 20px Sans"; ctx.fillStyle = "rgba(255,255,255,0.8)";
      ctx.fillText(`UID: ${uid}`, avX + avS + 30, avY + 72);

      // Balance
      ctx.font = "bold 44px Sans"; ctx.fillStyle = "#e7e7ff";
      ctx.fillText(`Balance: ${bal}$`, avX + avS + 30, avY + 150);

      // Footer
      ctx.font = "400 14px Sans";
      ctx.fillStyle = "rgba(255,255,255,0.55)";
      ctx.fillText("Generated by GoatBot", 44 + 36, 44 + h - 88 - 30);

      // Side text
      ctx.font = "400 16px Sans";
      ctx.fillStyle = "rgba(255,255,255,0.65)";
      ctx.fillText("Siyuu", w - 100, h - 40);

      const tmp = path.join(__dirname,"cache");
      await fs.ensureDir(tmp);
      const p = path.join(tmp, `bal_${uid}_${Date.now()}.png`);
      await fs.writeFile(p,canvas.toBuffer("image/png"));
      return p;
    }

    function roundRect(ctx,x,y,w,h,r,fill,stroke){
      if(typeof r==="undefined") r=5;
      if(typeof r==="number") r={tl:r,tr:r,br:r,bl:r};
      ctx.beginPath();
      ctx.moveTo(x+r.tl,y);
      ctx.lineTo(x+w-r.tr,y);
      ctx.quadraticCurveTo(x+w,y,x+w,y+r.tr);
      ctx.lineTo(x+w,y+h-r.br);
      ctx.quadraticCurveTo(x+w,y+h,x+w-r.br,y+h);
      ctx.lineTo(x+r.bl,y+h);
      ctx.quadraticCurveTo(x,y+h,x,y+h-r.bl);
      ctx.lineTo(x,y+r.tl);
      ctx.quadraticCurveTo(x,y,x+r.tl,y);
      ctx.closePath();
      if(fill) ctx.fill();
      if(stroke) ctx.stroke();
    }

    function getInitials(name){
      if(!name) return "U";
      const parts = name.split(" ").filter(Boolean);
      if(parts.length===1) return parts[0].slice(0,2).toUpperCase();
      return (parts[0][0]+parts[1][0]).toUpperCase();
    }
  }
};
